### ISSUE TITLE
Problem compiling opal.cpp

### ISSUE THREAD

**Issue by jaesvi** [isovic/seqlib#1]
Hi,
I have been having trouble with the compilation of seqlib, which is preventing me from installing and using GraphMap and Racon. The issue seems to be with opal.cpp, and it complains about some variables not being declared properly:
`/home/mhe/bin/gcc-4.8 -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -Icodebase/argparser/src -Icodebase/samscripts/src -Icodebase/spoa/src -Icodebase/seqlib/src -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread -march=native -o obj_linux/codebase/seqlib/src/libs/opal.o codebase/seqlib/src/libs/opal.cpp
codebase/seqlib/src/libs/opal.cpp: In function ‘int simdIsAllZeroes(const __mxxxi&)’:
codebase/seqlib/src/libs/opal.cpp:105:32: error: ‘_mm_testz_si128’ was not declared in this scope
     return _mmxxx_testz_si(a, a);`

Starting with "_mm_testz_si128" and continuing with a bunch of other of the same "_mm_" format.
What could be the problem?
Many thanks.

**Comment by isovic** [comment]
Hi Jaesvi,
Could you check and tell me the vendor and the model of your CPU? I want to check which SIMD instructions are implemented in you particular processor.
(less /proc/cpuinfo)
Also, if you could paste here the copy of the flags field in the above file for any of the CPUs, that would be of great help.
Thank you,
Best regards,
Ivan.

**Comment by jaesvi** [comment]
vendor_id: AuthenticAMD
model: 4
model name: Quad-Core AMD Opteron(tm) Processor 8376 HE
flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc pni cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy altmovcr8 abm sse4a misalignsse 3dnowprefetch osvw

Thanks a lot,
Jose

**Comment by isovic** [comment]
Dear Jaesvi,
I'm afraid your CPU might be a bit too old...it doesn't seem to support neither the SSE4.1 nor AVX2 instructions required by the Opal module.
Could you by any chance try running this on another architecture and let me know if everything went fine?

Best regards,
Ivan.

**Comment by jaesvi** [comment]
I managed to install it on a different computer. I have issues with Racon now but will post in the appropiate repository. Thanks for the help.
